### ISSUE TITLE
Segfault "[BUG] rb_gc_mark(): 0x... is T_ZOMBIE" under Ruby 2.1.2

### ISSUE THREAD

**Issue by dwo** [brianmario/yajl-ruby#145]
I've observed this segfault on Ruby 2.1.2 on Ubuntu Lucid (compiled from source) with yajl-ruby 1.2.0 and 1.2.1.

I am yet to reproduce this fully reliably, but I'll work on it. I am not sure whether it is specific JSON causing this, or just something to do with garbage collection timing (as I'm able to run the same code and it will only segfault maybe 1 out of 5 times).

Here are (what I think are) the relevant bits of output (redactions are shown as "[...]"):
```
[...]/shared/bundle/ruby/2.1.0/gems/yajl-ruby-1.2.1/lib/yajl.rb:37: [BUG] rb_gc_mark(): 0x007ff42d7c5f78 is T_ZOMBIE
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

[...]

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0088 e:000087 CFUNC  :parse
c:0020 p:0024 s:0083 e:000082 METHOD [...]/shared/bundle/ruby/2.1.0/gems/yajl-ruby-1.2.1/lib/yajl.rb:37
[...]

-- C level backtrace information -------------------------------------------
[...]
[...]/shared/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/yajl-ruby-1.2.1/yajl/yajl.so(+0x4063) [0x7ff427e04063] yajl_ext.c:327
[...]/shared/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/yajl-ruby-1.2.1/yajl/yajl.so(+0x599d) [0x7ff427e0599d] yajl_parser.c:351
[...]/shared/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/yajl-ruby-1.2.1/yajl/yajl.so(+0x37f4) [0x7ff427e037f4] yajl_ext.c:254
[...]
```
Here's the yajl-related bits of the backtrace from a core dump in gdb:
```
#0  0x00007fb22285bb65 in ssignal () from /lib/libc.so.6
#1  0x00007fff25a63e80 in ?? ()
[...]
#10 0x00007fb22390d9d3 in rgengc_check_relation (objspace=0x7fb226312b80, ptr=140403079313396) at gc.c:3555
#11 gc_mark (objspace=0x7fb226312b80, ptr=140403079313396) at gc.c:3584
#12 0x00007fb22390dc0b in mark_keyvalue (key=<value optimised out>, value=140403138408160, data=140733825040224) at gc.c:3361
#13 0x00007fb2239c0290 in st_foreach (table=0x7fb226e30450, func=0x7fb223ab01dc, arg=1) at st.c:1040
#14 0x00007fb22390eeae in gc_mark_children (objspace=0x7fb2253b2750, ptr=140403135784360) at gc.c:3950
#15 0x00007fb22390f157 in gc_mark_stacked_objects (objspace=0x7fb2253b2750, full_mark=<value optimised out>) at gc.c:3968
#16 gc_marks_body (objspace=0x7fb2253b2750, full_mark=<value optimised out>) at gc.c:4152
#17 0x00007fb2239116ba in gc_marks (objspace=0x7fb2253b2750, full_mark=<value optimised out>, immediate_sweep=0, reason=<value optimised out>) at gc.c:4513
#18 garbage_collect_body (objspace=0x7fb2253b2750, full_mark=<value optimised out>, immediate_sweep=0, reason=<value optimised out>) at gc.c:5011
#19 0x00007fb223912295 in heap_prepare_freepage (klass=140403105568360, flags=37, v1=<value optimised out>, v2=<value optimised out>, v3=140403079964416) at gc.c:1216
#20 heap_get_freeobj_from_next_freepage (klass=140403105568360, flags=37, v1=<value optimised out>, v2=<value optimised out>, v3=140403079964416) at gc.c:1234
#21 heap_get_freeobj (klass=140403105568360, flags=37, v1=<value optimised out>, v2=<value optimised out>, v3=140403079964416) at gc.c:1256
#22 newobj_of (klass=140403105568360, flags=37, v1=<value optimised out>, v2=<value optimised out>, v3=140403079964416) at gc.c:1300
#23 0x00007fb2239c3eb9 in str_alloc (klass=2950, 
    ptr=0x7fb21cb3e1f7 "[...]"..., len=6, termlen=1) at string.c:484
#24 str_new0 (klass=2950, 
    ptr=0x7fb21cb3e1f7 "[...]"..., len=6, termlen=1) at string.c:510
#25 0x00007fb21ee9c5a0 in yajl_found_string (ctx=0x7fb2271a4560, stringVal=0xb86 <Address 0xb86 out of bounds>, stringLen=2950) at yajl_ext.c:294
#26 0x00007fb21ee9dc32 in yajl_do_parse (hand=0x7fb2282bfd30, 
    jsonText=0x7fb21caf0010 "[...]"..., jsonTextLen=348607) at yajl_parser.c:258
#27 0x00007fb21ee9b7f4 in yajl_parse_chunk (argc=<value optimised out>, argv=<value optimised out>, self=140403136939360) at yajl_ext.c:254
[...]
```

Any ideas about what else I could investigate or provide to track down the cause?

**Comment by dwo** [comment]
I did try to get a reduced example for this, but never got to the bottom of it. The more I reduced the code to try and find the root cause, the less likely it became to happen.

My solution is probably to be to use https://github.com/ohler55/oj instead. ¯\_(ツ)_/¯

**Comment by dwo** [comment]
I confirmed that this is probably a ruby bug (not a yajl bug) because Oj gets the exact same error.

**Comment by oskarpearson** [comment]
I know that this is a very old issue - but I thought I'd comment in case anyone else ends up here with the same error:

I've been working on the same codebase as @dwo - and it seems that libxml-ruby from 2.8.0 to 2.9.0 fixes the issue (though only time will tell).

My best guess is that the native libxml-ruby extension creates zombie objects, which are then GCed when Yajl parses something.

**Comment by saleandro** [comment]
Following up on Oskar's comment: unfortunately it still happens for us, but definitely not a Yajl issue, as we have since removed it from the project.
