### ISSUE TITLE
Fluentd setup on Solaris 10 - yajl.so (LoadError)

### ISSUE THREAD

**Issue by dmitriklein** [brianmario/yajl-ruby#206]
# fluentd --setup ./fluent
/opt/csw/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': ld.so.1: ruby2.0: fatal: relocation error: file /opt/csw/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.0.0/lib/yajl/yajl.so: symbol isinf: referenced symbol not found - /opt/csw/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.0.0/lib/yajl/yajl.so (LoadError)
        from /opt/csw/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/csw/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.0.0/lib/yajl.rb:1:in `<top (required)>'

====

# gem list --local

*** LOCAL GEMS ***

bigdecimal (default: 1.2.0)
bundle (0.0.1)
bundler (1.17.3, default: 1.16.6)
bundler-unload (1.0.2)
concurrent-ruby (1.1.9)
cool.io (1.7.1)
executable-hooks (1.6.1)
fileutils2 (0.2.0)
fluentd (0.12.43)
gem-compiler (0.5.0)
http_parser.rb (0.8.0, 0.6.0)
io-console (default: 0.4.2)
json (2.5.0, default: 1.7.7)
minitest (default: 4.3.2)
msgpack (1.3.3)
pkg-config (1.4.6)
psych (2.2.4, default: 2.0.0)
rake (default: 0.9.6)
rake-compiler (1.1.6)
rake-compiler-dock (1.1.0)
rdoc (default: 4.0.0)
rspec (3.10.0)
rubygems-bundler (1.4.5)
rubygems-update (2.7.11)
rubysl-fileutils (2.0.3)
serverengine (1.6.4)
sigdump (0.2.4)
string-scrub (0.0.4)
strptime (0.2.5)
test-unit (default: 2.0.0.0)
tzinfo (2.0.4)
tzinfo-data (1.2021.5)
webrick (1.3.1)
yajl-ruby (1.0.0)
yard (0.9.27)
#

**Comment by dmitriklein** [comment]
# gem install yajl-ruby-1.4.1.gem
Building native extensions. This could take a while...
Successfully installed yajl-ruby-1.4.1
Parsing documentation for yajl-ruby-1.4.1
unable to convert "\x84" from ASCII-8BIT to UTF-8 for /opt/csw/lib/ruby/gems/2.0.0/extensions/x86-solaris-2.10/2.0.0/yajl-ruby-1.4.1/yajl/yajl.so, skipping
unable to convert "\x84" from ASCII-8BIT to UTF-8 for lib/yajl/yajl.so, skipping
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://api.rubygems.org/specs.4.8.gz)
1 gem installed
#
